PGG106/Alexandria

src/hashkey.cpp, src/init.cpp, src/search.cpp, src/uci.cpp
RFP (reverse futility pruning) is now used to cut child nodes when their expected value is too low to transpose into a meaningful position, this commit gains around 25 elo over the previous version 
Score of Alexandria-new vs Alexandria: 283 - 167 - 1050 [0.539]
...      Alexandria-new playing White: 186 - 57 - 507  [0.586] 750
...      Alexandria-new playing Black: 97 - 110 - 543  [0.491] 750
...      White vs Black: 296 - 154 - 1050  [0.547] 1500
Elo difference: 26.9 +/- 9.6, LOS: 100.0 %, DrawRatio: 70.0 %
1500 of 1500 games finished.
=> Introduce RFP

src/History.cpp, src/search.cpp
STC 10.0+0.1
ELO   | 8.48 +- 5.48 (95%)
LLR   | 3.02 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 7048 W: 1700 L: 1528 D: 3820
LTC 40/720
Score of Alexandria2.3.2 vs Alexandria-2.3.1: 12 - 4 - 35 [0.578]
...      Alexandria2.3.2 playing White: 8 - 0 - 18  [0.654] 26
...      Alexandria2.3.2 playing Black: 4 - 4 - 17  [0.500] 25
...      White vs Black: 12 - 4 - 35  [0.578] 51
Elo difference: 55.0 +/- 52.9, LOS: 97.7 %, DrawRatio: 68.6 %
51 of 10000 games finished.
More tests are needed at ltc but it appears to be a positive change and to scale with time control length
=> Fix move ordering scores

src/search.cpp
ELO   | 6.23 +- 4.37 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 9712 W: 2030 L: 1856 D: 5826
=> Reduce more on non-pv nodes (LMR)

src/search.cpp
ELO   | 16.44 +- 7.43 (95%)
GAMES | N: 2856 W: 554 L: 419 D: 1883
=> Skip bad captures in QSearch based on SEE score

src/search.cpp
ELO   | 10.52 +- 6.42 (95%)
GAMES | N: 5384 W: 1373 L: 1210 D: 2801
=> Save original static eval and use it in place of search score when appropriate

src/search.cpp
ELO   | 12.82 +- 7.12 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 4256 W: 1071 L: 914 D: 2271
=> stop checking if move exists before returning tt score

src/Board.h, src/search.cpp
Bench: 7975212
ELO   | 11.48 +- 6.88 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 5056 W: 1388 L: 1221 D: 2447
ELO   | 17.51 +- 9.82 (95%)
LLR   | 2.25 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 2264 W: 590 L: 476 D: 1198
=> Search extension

src/search.cpp
Bench: 5299844
ELO   | 5.36 +- 4.10 (95%)
GAMES | N: 13496 W: 3410 L: 3202 D: 6884
=> Prevent dropping into Qsearch if in check

src/uci.cpp
Bench: 5398962
The engine was tested up to 16 threads thanks to Plutie from the OB discord, this is realistically the most threads i'll manage to get it tested with.
```Score of alexandria-16t vs alexandria-4t: 937 - 275 - 490  [0.694] 1702
...      alexandria-16t playing White: 607 - 58 - 186  [0.823] 851
...      alexandria-16t playing Black: 330 - 217 - 304  [0.566] 851
...      White vs Black: 824 - 388 - 490  [0.628] 1702
Elo difference: 142.6 +/- 14.6, LOS: 100.0 %, DrawRatio: 28.8 %
```
I also ran an STC regression test against 3.1.0 because i fear it might have regressed and i'm glad to say it did not
```ELO   | 20.21 +- 5.11 (95%)
CONF  | 10.0+0.10s Threads=1 Hash=8MB
GAMES | N: 7968 W: 2025 L: 1562 D: 4381
```
=> Increase threads limit to 256

src/search.cpp
Possibly introduces a small regression but it should make working with lmr a bit easier 
ELO   | -2.14 +- 3.24 (95%)
LLR   | -0.41 (-2.94, 2.94) [-5.00, 0.00]
GAMES | N: 21408 W: 5136 L: 5268 D: 11004
Bench: 5775606
=> Avoid LMR dropping into Qsearch or extending

src/board.h, src/init.cpp, src/uci.cpp
ELO   | 9.94 +- 4.94 (95%)
LLR   | 2.99 (-2.94, 2.94) [0.00, 3.00]
GAMES | N: 8848 W: 2191 L: 1938 D: 4719
=> Tweak lmp and see pruning margins

src/time_manager.cpp
```
ELO   | 14.56 +- 6.31 (95%)
SPRT  | 40/8.0+0.00s Threads=1 Hash=32MB
GAMES | N: 5944 W: 1643 L: 1394 D: 2907
```
```
ELO   | 12.89 +- 5.80 (95%)
SPRT  | 40/20.0+0.00s Threads=1 Hash=128MB
GAMES | N: 6688 W: 1751 L: 1503 D: 3434
```
Bench: 2506626
=> Improve TM for Cyclic time controls

src/search.cpp
ELO   | 4.97 +- 3.38 (95%)
GAMES | N: 20832 W: 5493 L: 5195 D: 10144
Bench: 2743847
=> Decrease the LMR reduction for moves that have a good history score

src/search.cpp
ELO   | 6.21 +- 3.84 (95%)
GAMES | N: 15544 W: 3993 L: 3715 D: 7836
ELO   | 7.67 +- 4.33 (95%)
GAMES | N: 12008 W: 3058 L: 2793 D: 6157
=> Extend LMR to also cover tactical moves 

src/search.cpp
ELO   | 3.18 +- 2.45 (95%)
GAMES | N: 38112 W: 9591 L: 9242 D: 19279
Bench: 2839773
=> Use total moves played instead of just quiet moves for the lmp margin

src/search.cpp
ELO   | 4.53 +- 3.15 (95%)
GAMES | N: 23240 W: 5942 L: 5639 D: 11659
=> Remove depth limit from razoring 

src/board.h, src/search.cpp, src/search.h, src/time_manager.cpp
A big thanks to Kimmy from the Koivisto team for getting me to look at this again.
ELO   | 19.84 +- 7.39 (95%)
GAMES | N: 4224 W: 1171 L: 930 D: 2123
ELO   | 15.86 +- 6.46 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 3.00]
GAMES | N: 5392 W: 1431 L: 1185 D: 2776
=> Scale time used for a search based on the percent of nodes spent searching the best move

Contributors, src/search.cpp
bench: 3254082
STC:
ELO   | 6.79 +- 4.06 (95%)
GAMES | N: 13928 W: 3590 L: 3318 D: 7020
https://chess.swehosting.se/test/1284/
LTC:
ELO   | 9.40 +- 4.85 (95%)
GAMES | N: 9464 W: 2403 L: 2147 D: 4914
https://chess.swehosting.se/test/1291/
=> Do LMP at higher depths

src/history.cpp, src/search.cpp, src/search.h
ELO   | 4.82 +- 3.29 (95%)
GAMES | N: 21392 W: 5497 L: 5200 D: 10695
ELO   | 5.48 +- 3.52 (95%)
GAMES | N: 17768 W: 4370 L: 4090 D: 9308
=> Change history heuristic table

src/time_manager.cpp
ELO   | 3.65 +- 2.69 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
GAMES | N: 31336 W: 7856 L: 7527 D: 15953
ELO   | 4.05 +- 2.90 (95%)
GAMES | N: 26712 W: 6631 L: 6320 D: 13761
=> Use a bigger fraction of the increment for TMs that have one 

src/search.cpp
ELO   | 3.34 +- 2.53 (95%)
GAMES | N: 35496 W: 8922 L: 8581 D: 17993
ELO   | 2.96 +- 2.57 (95%)
LLR   | 2.36 (-2.94, 2.94) [0.00, 3.00]
GAMES | N: 33576 W: 8211 L: 7925 D: 17440
Bench: 3449068
=> Increase lmr reduction for moves with a bad history score

src/search.cpp
Prevents some weird interactions with capture history
ELO   | 1.47 +- 4.25 (95%)
LLR   | 0.17 (-2.94, 2.94) [0.00, 3.00]
GAMES | N: 12528 W: 3086 L: 3033 D: 6409
Bench: 8868607
=> Move bad captures after all quiet moves, no matter the history score

src/search.cpp
ELO   | 2.62 +- 2.08 (95%)
GAMES | N: 51032 W: 12356 L: 11971 D: 26705
Bench: 7862837
=> LMR even when in check

src/search.cpp
ELO   | 2.61 +- 2.07 (95%)
GAMES | N: 51992 W: 12751 L: 12361 D: 26880
Bench: 8520603
=> Reduce moves that give check less

src/history.cpp
fix a bug where the second layer of conthist was never used, big thanks to @lucametehau for spotting this
ELO   | 7.52 +- 4.27 (95%)
GAMES | N: 12192 W: 3058 L: 2794 D: 6340
Bench: 8348998
=> Fix continuation history

src/search.cpp
ELO   | 3.07 +- 2.37 (95%)
GAMES | N: 39872 W: 9829 L: 9477 D: 20566
Bench: 8120688
=> Don't do stand pat when in check, generate quiet check evasions in qsearch

src/search.cpp
ELO   | 1.06 +- 2.63 (95%)
LLR   | 2.93 (-2.94, 2.94) [-3.00, 1.00]
GAMES | N: 32528 W: 7944 L: 7845 D: 16739
=> Propagate mate scores from Qsearch

src/search.cpp
ELO   | 7.77 +- 4.38 (95%)
GAMES | N: 11808 W: 3018 L: 2754 D: 6036
Bench: 9960849
=> Do IIR on positions without a TThit instead of positions without a TT move

src/search.cpp
Reworks check extension to allow a drop into Qsearch and to make it fall under the maximum extension limit applied to SE
ELO   | 1.50 +- 2.51 (95%)
LLR   | 0.53 (-2.94, 2.94) [0.00, 3.00]
GAMES | N: 36256 W: 9000 L: 8843 D: 18413
Adjusted LLR with non regr [-3, 1] bounds: 4.06
Bench: 9232576
=> Rework check extension

src/search.cpp
ELO   | 2.93 +- 2.28 (95%)
GAMES | N: 42912 W: 10508 L: 10146 D: 22258
Bench: 9042370
=> Decrease search depth in AWSearch on a fail high 

src/search.cpp
=> Fix adjusted eval being saved as static eval in the TT during Qsearch

src/search.cpp, src/types.h
ELO   | 6.05 +- 3.79 (95%)
GAMES | N: 16128 W: 4177 L: 3896 D: 8055
ELO   | 8.46 +- 4.54 (95%)
GAMES | N: 10520 W: 2596 L: 2340 D: 5584
Bench: 11544359
=> Tweak singularBeta

src/search.cpp
Tested at 20+0.2:
```
ELO   | 7.42 +- 4.21 (95%)
SPRT  | 20.0+0.20s Threads=1 Hash=16MB
GAMES | N: 12224 W: 2992 L: 2731 D: 6501
```
https://chess.swehosting.se/test/3191/
Bench: 12889204
=> Do more singular extensions

src/search.cpp, src/types.h
```
ELO   | 2.59 +- 2.06 (95%)
GAMES | N: 52096 W: 12634 L: 12246 D: 27216
https://chess.swehosting.se/test/3257/
```
Bench 13200360
=> Do more double extensions

src/search.cpp
ELO   | 5.20 +- 3.42 (95%)
GAMES | N: 19120 W: 4753 L: 4467 D: 9900
https://chess.swehosting.se/test/3323/
Bench: 11581833
=> Do one less full move for lmr

src/search.cpp, src/search.h
```
python sprt.py -w 5358 -l 5335 -d 12139 -e0  -5 -e1 0
ELO: 0.35 +- 3.08 [-2.73, 3.43]
LLR: 3.1 [-5.0, 0.0] (-2.94, 2.94)
H1 Accepted
```
Bench 11581640
=> Identify PV nodes more accurately.

src/board.cpp, src/nnue.cpp, src/nnue.h, src/search.cpp, src/types.h
Avoids having to supply a copy of the nnue params to each and any thread data object
=> Use global nnue params

src/search.cpp
```
ELO   | 1.82 +- 1.93 (95%)
LLR   | 7.48 [-3.0, 1.0] (-2.94, 2.94)
GAMES | N: 58048 W: 13712 L: 13408 D: 30928
```
=> Mate-Guard for Moves-Loop Pruning.

src/search.cpp, src/search.h, src/types.h
```
ELO: -0.404 +- 2.29 [-2.69, 1.88]
LLR: 3.22 [-5.0, 1.0] (-2.94, 2.94)
GAMES | N: 41248 W: 9586 L: 9634 D: 22028
```
=> Introduce verification search to detect zugzwangs

src/search.cpp, src/ttable.cpp, src/ttable.h, src/types.h
ELO   | 1.08 +- 2.58 (95%)
LLR   | 2.94 (-2.25, 2.89) [-3.00, 1.00]
GAMES | N: 32240 W: 7557 L: 7457 D: 17226
Bench: 11074335
=> Increase TTKey size to 32 bits

src/io.cpp, src/search.cpp, src/search.h, src/ttable.h, src/types.h
Also includes other cleanups and simplifications.
```
ELO   | 0.07 +- 1.73 (95%)
LLR   | 2.90 (-2.25, 2.89) [-3.00, 1.00]
GAMES | N: 72800 W: 17133 L: 17119 D: 38548
https://chess.swehosting.se/test/3746/
```
Bench 11074335
=> Prevent wrong TT flags when not TT hit

src/board.cpp, src/eval.cpp, src/types.h
ELO   | 2.61 +- 2.09 (95%)
GAMES | N: 50336 W: 12150 L: 11772 D: 26414
Bench: 8753317
=> Dampen Eval as the 50 move rule approaches

src/search.cpp, src/types.h
```
ELO   | 5.49 +- 3.56 (95%)
GAMES | N: 17472 W: 4329 L: 4053 D: 9090
https://chess.swehosting.se/test/3855/
```
=> Tweak conditions required to perform NMP

src/history.cpp, src/types.h
ELO   | 2.81 +- 2.23 (95%)
GAMES | N: 45056 W: 11115 L: 10751 D: 23190
https://chess.swehosting.se/test/3910/
=> Extend continuation history to 4 plies

src/search.cpp, src/types.h
ELO   | 2.93 +- 2.29 (95%)
LLR   | 2.96 (-2.25, 2.89) [0.00, 3.00]
GAMES | N: 42624 W: 10444 L: 10084 D: 22096
shorter tc test with adj off
ELO   | 5.63 +- 3.92 (95%)
SPRT  | 5.0+0.05s Threads=1 Hash=16MB
LLR   | 2.49 (-2.25, 2.89) [0.00, 3.00]
GAMES | N: 14624 W: 3664 L: 3427 D: 7533
Bench: 9577041
=> Reintroduce Razoring

src/search.cpp, src/types.h
* use in_check variable previously declared instead of pos->checkers for check extensions
* make root_node a bool (I think it was intended as a bool, and is used as a bool)
Bench 9577041
=> Small cleanups

src/history.h, src/search.cpp, src/types.h
ELO   | 5.49 +- 3.54 (95%)
GAMES | N: 17344 W: 4218 L: 3944 D: 9182
https://chess.swehosting.se/test/3996/
Bench 8025673
=> Update continuation histories for post LMR searches

src/search.cpp, src/types.h
```
ELO   | -0.02 +- 1.66 (95%)
GAMES | N: 81280 W: 19767 L: 19771 D: 41742
https://chess.swehosting.se/test/4060/
```
Bench 9302937
=> Simplify full-window research condition

src/search.cpp, src/types.h
ELO   | -0.01 +- 2.93 (95%)
LLR   | 2.91 (-2.25, 2.89) [-5.00, 0.00]
GAMES | N: 25632 W: 6106 L: 6107 D: 13419
https://chess.swehosting.se/test/4114/
=> Fix incorrect stack init 

src/board.cpp, src/history.cpp, src/search.cpp, src/types.h
ELO   | 2.80 +- 2.22 (95%)
GAMES | N: 44640 W: 10812 L: 10452 D: 23376
https://chess.swehosting.se/test/4224/
Bench: 9065622
=> Extend Capthist to promotions, use Capthist to tweak LMR reduction

src/search.cpp
ELO   | 1.89 +- 1.52 (95%)
GAMES | N: 96128 W: 23238 L: 22715 D: 50175
Bench: 8553581
=> Decouple noisy and quiet moves lmr reductions

src/search.cpp, src/types.h
Idea from black marlin (and boychesser). 
```
ELO   | 5.52 +- 3.59 (95%)
GAMES | N: 17312 W: 4302 L: 4027 D: 8983
https://chess.swehosting.se/test/4397/
```
Bench 8547310
=> Do more history updates if eval <= alpha

src/history.cpp, src/search.cpp, src/types.h
ELO   | 2.43 +- 1.96 (95%)
GAMES | N: 58432 W: 14380 L: 13972 D: 30080
https://chess.swehosting.se/test/4459/
Bench 8452237
=> Tweak history updates

src/ttable.cpp
ELO   | 1.16 +- 2.71 (95%)
GAMES | N: 30576 W: 7484 L: 7382 D: 15710
Bench: 9037635
=> Use a less deranged replacement scheme

src/time_manager.cpp, src/types.h
ELO   | 3.97 +- 2.89 (95%)
GAMES | N: 26720 W: 6591 L: 6286 D: 13843
Bench: 7765821
=> Improve NodeTm scaling

src/search.cpp, src/types.h
ELO   | 1.98 +- 1.59 (95%)
GAMES | N: 88256 W: 21557 L: 21054 D: 45645
https://chess.swehosting.se/test/4663/
Bench 8913775
=> Add futility pruning to qsearch

src/search.cpp, src/types.h
ELO   | 3.71 +- 2.74 (95%)
GAMES | N: 29888 W: 7405 L: 7086 D: 15397
https://chess.swehosting.se/test/4704/
Bench: 7799933
=> Fix countermoves usage in move ordering

src/init.cpp, src/search.cpp
Also requires adjustments to lmrDepth coefficients.
ELO   | 0.48 +- 1.70 (95%)
LLR   | -1.76 (-2.25, 2.89) [0.00, 3.00]
GAMES | N: 76512 W: 18331 L: 18225 D: 39956
https://chess.swehosting.se/test/5037/
However, it passes [-3, 1] with a 4.66 LLR.
Bench: 8236697
=> Rebalance and simplify LMR formula

src/search.cpp, src/types.h
this was already basically non functional, the first depth at which the guard did something was 9, that meant 84 moves for a node where improving was true and 42 for a node where it was false.
Passed STC non regr 
```
Elo   | 1.47 +- 3.13 (95%)
LLR   | 2.94 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 22930 W: 5622 L: 5525 D: 11783
Penta | [111, 2526, 6087, 2637, 104]
```
Got tired of waiting for LTC non regr
```
Elo   | 2.24 +- 4.05 (95%)
LLR   | 2.46 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 13048 W: 3068 L: 2984 D: 6996
Penta | [21, 1358, 3681, 1444, 20]
```
=> Simplify depth guard for lmp

src/board.cpp, src/board.h, src/makemove.cpp, src/search.cpp, src/types.h
Swaps out old 3fold detection code for a version that is more efficient, better explained, and less awful to look at.
Improvements include not looking further than the last null move, since that too is irreversible, scanning backwards instead of forwards since repetitions are more likely to have happened in recent plies and only checking positions with a matching side to move.
Bench: 6645600
=> Improve 3fold detection

src/time_manager.cpp, src/types.h
I have no idea why we were using that awful tm code for regular time controls
STC:
```
Elo   | 12.26 +- 6.54 (95%)
Games | N: 5244 W: 1363 L: 1178 D: 2703
Penta | [20, 506, 1386, 689, 21]
```
Note: at STC this patch only exacerbate the existing time out issue, with the entire test having 13 time outs (10 from the dev version).
LTC:
```
Elo   | 4.52 +- 3.83 (95%)
Games | N: 14612 W: 3473 L: 3283 D: 7856
Penta | [16, 1499, 4094, 1673, 24]
```
Note: no time out noticed at LTC.
=> Align TM code for X+Y to the one used for cyclic time controls

src/search.cpp
The initial version of the code used the same search for either a skipped lmr or a lmr that failed high. This was fine when the logic for both this searches was the same but with the introduction of doDeeper the 2 have diverged, splitting the 2 makes the code easier to parse
=> Improve LMR logic separation

src/search.cpp
```
ELO   | 1.08 +- 2.41 (95%)
LLR   | -0.02 (-2.25, 2.89) [0.00, 3.00]
GAMES | N: 38272 W: 9241 L: 9122 D: 19909
https://chess.swehosting.se/test/5312/
```
Passed nonreg:
```
$ python3 sprt.py --wins 9241 --losses 9122 --draws 19909 --elo0 -3 --elo1 1
ELO: 1.08 +- 2.41 [-1.33, 3.49]
LLR: 3.49 [-3.0, 1.0] (-2.94, 2.94)
H1 Accepted
```
Bench 7513941
=> Clear killers and excluded move properly

src/search.cpp, src/types.h
Same logic as https://github.com/official-stockfish/Stockfish/commit/e551964ef63e4e4af4bb6132538b98fad4a51afe
```
ELO   | 3.59 +- 2.66 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 3.00]
GAMES | N: 31264 W: 7653 L: 7330 D: 16281
https://chess.swehosting.se/test/5349/
```
=> Do negative extensions on expected cut nodes 

src/search.cpp, src/types.h
Same logic as https://github.com/official-stockfish/Stockfish/commit/e551964ef63e4e4af4bb6132538b98fad4a51afe
ELO   | 3.59 +- 2.66 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 3.00]
GAMES | N: 31264 W: 7653 L: 7330 D: 16281
https://chess.swehosting.se/test/5349/
Bench 6772197
=> Do negative extensions on expected cut nodes  (#310)

src/search.cpp, src/types.h
ELO   | 5.55 +- 3.55 (95%)
GAMES | N: 17088 W: 4113 L: 3840 D: 9135
https://chess.swehosting.se/test/5402/
Bench: 5853137
=> Combine 2 separate failed LMR patches

src/search.cpp, src/types.h
ELO   | 2.50 +- 2.01 (95%)
GAMES | N: 53408 W: 12670 L: 12286 D: 28452
https://chess.swehosting.se/test/5439/
Bench 6445111
=> Tweak parameters for reverse futility pruning

src/board.cpp, src/board.h, src/search.cpp, src/types.h
Inspired by Koivisto, and I found out about it in Berserk
Elo   | 2.57 +- 2.52 (95%)
Games | N: 34402 W: 8252 L: 7998 D: 18152
Penta | [141, 3919, 8831, 4165, 145]
https://antares2262.pythonanywhere.com/test/111/
Bench 7033692
=> Increase futility margin if the opponent has a guaranteed SEE > 0

src/time_manager.cpp, src/types.h
Tune: https://antares2262.pythonanywhere.com/tune/109/
STC:
Elo   | 4.93 +- 3.89 (95%)
Games | N: 14586 W: 3589 L: 3382 D: 7615
Penta | [69, 1524, 3887, 1757, 56]
https://antares2262.pythonanywhere.com/test/113/
LTC:
Elo   | 6.82 +- 4.81 (95%)
Games | N: 8972 W: 2097 L: 1921 D: 4954
Penta | [6, 844, 2617, 1006, 13]
https://antares2262.pythonanywhere.com/test/117/
Bench 7033692
=> Tune time management using SPSA

src/search.cpp, src/types.h
Triple instead of double extend quiet ttMoves with singular score far below singular beta. This threshold value is initially set to 300, there is scope for more scaling by reducing it.
Passed LTC:
https://chess.swehosting.se/test/5460/
ELO   | 1.92 +- 1.56 (95%)
SPRT  | 16.0+0.16s Threads=1 Hash=32MB
GAMES | N: 86848 W: 20054 L: 19573 D: 47221
Bench 7197125
=> Introduce Triple Extensions

src/movepicker.cpp, src/movepicker.h, src/search.cpp, src/types.h
Elo   | 2.55 +- 2.55 (95%)
SPRT  | 16.0+0.16s Threads=1 Hash=16MB
Games | N: 33278 W: 7934 L: 7690 D: 17654
Penta | [97, 3684, 8822, 3950, 86]
https://chess.swehosting.se/test/5514/
Bench 6948840
=> Use move history in SEE threshold for move ordering

src/search.cpp, src/types.h
Elo   | 2.19 +- 2.27 (95%)
Games | N: 43536 W: 10656 L: 10381 D: 22499
Penta | [167, 4980, 11228, 5197, 196]
https://chess.swehosting.se/test/5531/
Bench 6545109
=> Combine 2 parameter tweaks

src/search.cpp, src/types.h
Elo   | 2.75 +- 2.64 (95%)
Games | N: 31414 W: 7558 L: 7309 D: 16547
Penta | [136, 3592, 8015, 3815, 149]
https://chess.swehosting.se/test/5595/
Bench 6110305
=> Increment depth when we double extend at low depths

src/search.cpp, src/ttable.cpp, src/ttable.h, src/types.h, src/uci.cpp
Elo   | 2.50 +- 2.47 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 35524 W: 8468 L: 8212 D: 18844
Penta | [143, 3983, 9263, 4221, 152]
https://chess.swehosting.se/test/5680/
Bench 6601039
=> Age TT entries and use it in our replacement scheme

src/history.cpp, src/history.h
Elo   | 2.06 +- 3.50 (95%)
LLR   | 2.95 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 17734 W: 4209 L: 4104 D: 9421
Penta | [66, 2004, 4633, 2087, 77]
https://chess.swehosting.se/test/5701/
Bench 6324387
=> Clamp continuation history properly

makefile, src/nnue.cpp, src/nnue.h
clang/clang++ does not support the -Wlogical-op flag, so only enable it for g++.
=> Fix clang compilation somewhat

makefile
Warnings are already disabled on clang so this is unneeded. Bench 6550747
=> Revert "Fix clang compilation somewhat (#365)"

src/eval.cpp, src/movepicker.cpp, src/position.cpp, src/position.h, src/search.cpp, src/types.h
Elo   | 2.99 +- 2.78 (95%)
Games | N: 28500 W: 6897 L: 6652 D: 14951
Penta | [112, 3374, 7057, 3571, 136]
https://chess.swehosting.se/test/5879/
Bench 5839928
=> Split SEE and material values and tweak each

src/eval.cpp, src/movepicker.cpp, src/position.cpp, src/position.h, src/search.cpp, src/types.h
Elo | 2.99 +- 2.78 (95%)
SPRT | 8.0+0.08s Threads=1 Hash=16MB
LLR | 2.95 (-2.94, 2.94) [0.00, 3.00]
Games | N: 28500 W: 6897 L: 6652 D: 14951
Penta | [112, 3374, 7057, 3571, 136]
https://chess.swehosting.se/test/5879/
Bench 5839928
=> Split SEE and material values and tweak each (#374)

src/history.cpp, src/history.h, src/search.cpp, src/search.h
Elo   | 2.85 +- 4.02 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 13788 W: 3374 L: 3261 D: 7153
Penta | [48, 1587, 3517, 1688, 54]
https://chess.swehosting.se/test/6106/
Bench 6027240
=> Put continuation history entries on the stack

src/position.cpp, src/position.h, src/search.cpp, src/types.h
It now handles promotions, en passant and castling correctly. Correct promotion handling also allows us to enable it for qsearch pruning.
Elo   | 2.46 +- 2.47 (95%)
Games | N: 36390 W: 8839 L: 8581 D: 18970
Penta | [136, 4182, 9307, 4428, 142]
https://chess.swehosting.se/test/6125/
Bench 5639746
=> Make SEE more accurate

Contributors, src/random.cpp, src/random.h, src/ttable.cpp
Fix moves being unpacked incorrectly from the TT if the first bit is a 1.
Passed non-regression STC:
Elo   | 0.83 +- 2.52 (95%)
LLR   | 2.94 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 34140 W: 8030 L: 7948 D: 18162
Penta | [129, 4067, 8599, 4143, 132]
https://chess.swehosting.se/test/6350
This also simplifies the random number generator, on request :)
=> Move unpack fix

src/makemove.cpp, src/types.h
This  is one of the worst pieces of code i have ever written, it greatly increases code duplication for the sake of removing some branching, sadly this gains Elo 
Elo   | 1.69 +- 1.85 (95%)
Games | N: 63340 W: 15081 L: 14772 D: 33487
Penta | [200, 7047, 16859, 7372, 192]
=> Use a specialized makemove function for each movetype

src/init.cpp, src/search.cpp
The lmr reduction init loop was using a misleading name, `maxdepth`, even when the field wasn't indexed with depth but total moves, at the same time if totalmoves ever reached a value > 127 (extremely unlikely given lmp and more but potentially possible, especially in an engine with less pruning) the table would index OOB, this removes the misleading name and caps the reduction index.
passed stc non reg
Elo   | 5.12 +- 6.19 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 5428 W: 1259 L: 1179 D: 2990
Penta | [11, 546, 1522, 622, 13]
https://chess.swehosting.se/test/6562/
=> Limit lmr reductions to totalmove 63

src/search.cpp, src/ttable.cpp, src/types.h
Elo   | 1.90 +- 1.50 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
Games | N: 54578 W: 12713 L: 12414 D: 29451
Penta | [167, 6383, 13913, 6636, 190]
https://chess.swehosting.se/test/6759/
Bench 7027744
=> Save static eval for non TT hits in qsearch

src/init.cpp, src/position.h, src/search.cpp, src/search.h, src/types.h
Shrink some tables to reduce memory footprint
Elo   | 0.43 +- 1.56 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 48234 W: 11100 L: 11040 D: 26094
Penta | [162, 5452, 12806, 5558, 139]
https://chess.swehosting.se/test/6771/
Bench 7027744
=> Increase max ply to 256

src/movepicker.cpp, src/search.cpp
Elo   | 1.04 +- 2.05 (95%)
LLR   | 2.96 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 29794 W: 6860 L: 6771 D: 16163
Penta | [97, 3571, 7493, 3618, 118]
Elo   | 1.10 +- 2.00 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 27446 W: 5893 L: 5806 D: 15747
Penta | [14, 3157, 7295, 3242, 15]
Bench: 6519222
=> Simplify SEE threshold

src/ttable.h, src/types.h
Elo   | 1.59 +- 1.29 (95%)
Games | N: 72110 W: 16708 L: 16377 D: 39025
Penta | [244, 8134, 18954, 8493, 230]
https://chess.swehosting.se/test/6774/
Bench 6519222
=> Align TT buckets

src/history.cpp, src/move.h, src/movegen.cpp
This fixes 3 warnings due to the recent change to the Move type.
warning: comparison of integer expressions of different signedness
=> fix unsigned signed comparison warnings

src/ttable.cpp, src/ttable.h, src/types.h
Aligned to 2MB (if Huge Pages are available) otherwise 4KB.
Elo   | 2.93 +- 2.05 (95%)
Games | N: 27270 W: 6424 L: 6194 D: 14652
Penta | [84, 2932, 7373, 3162, 84]
https://chess.swehosting.se/test/6956/
Bench 5825700
=> Align the TT

src/history.cpp, src/movepicker.cpp, src/search.cpp
Elo   | 0.22 +- 1.41 (95%)
LLR   | -1.69 (-2.94, 2.94) [0.00, 3.00]
Games | N: 62788 W: 14648 L: 14609 D: 33531
Penta | [229, 7464, 15966, 7509, 226]
https://chess.swehosting.se/test/6970/
Passed Non-reg: 
$ python3 sprt.py --wins 14648 --losses 14609 --draws 33531 --elo0 -3 --elo1 1
ELO: 0.216 +- 1.85 [-1.64, 2.07]
LLR: 2.97 [-3.0, 1.0] (-2.94, 2.94)
H1 Accepted
Bench 6566135
=> Simplify history and tweak some parameters

src/cuckoo.h, src/ttable.cpp, src/uci.h
Make MultiPV static constexpr for now as it is unimplemented
Fix missing #pragma once in cuckoo.h
Fix including system header with "" instead of <> in ttable.cpp
=> small changes

src/history.cpp, src/history.h, src/io.cpp, src/makemove.cpp, src/makemove.h, src/position.cpp, src/position.h, src/search.cpp, src/search.h, src/types.h
Inspired by approaches from Seer and Caissa. Thanks to Vizvezdenec for giving some tips on the implementation
STC:
Elo   | 11.29 +- 4.66 (95%)
Games | N: 6034 W: 1557 L: 1361 D: 3116
Penta | [20, 659, 1481, 819, 38]
https://chess.swehosting.se/test/6994/
LTC:
Elo   | 12.40 +- 4.69 (95%)
Games | N: 4988 W: 1166 L: 988 D: 2834
Penta | [1, 499, 1318, 673, 3]
https://chess.swehosting.se/test/7006/
Bench 6324052
=> Introduce correction history

src/search.cpp
=> Properly initialize static eval when excludedMove is set 

src/history.cpp, src/history.h, src/types.h
1. Increase correction history limits
2. Scale correction history updates quadratically based on depth
Passed STC:
Elo   | 2.70 +- 2.00 (95%)
Games | N: 32136 W: 7815 L: 7565 D: 16756
Penta | [131, 3801, 7974, 4011, 151]
https://chess.swehosting.se/test/7128/
Passed LTC:
Elo   | 3.20 +- 2.20 (95%)
Games | N: 23590 W: 5374 L: 5157 D: 13059
Penta | [21, 2710, 6127, 2905, 32]
https://chess.swehosting.se/test/7142/
Bench 6118297
=> Combine 2 correction history patches

src/search.cpp
This condition is unnecessary due to the earlier `else if (excludedMove)`. No functional changes. Credits to @liamt19 for pointing this out on SF Discord.
Bench: 6118297
=> Remove Unnecessary Branching

src/search.cpp
This isn't striclty a simplification, it actually adds code, adding an additional branch in the code that evaluates what the lmr reduction should be. 
The reason i believe this to be desireable under non regr bounds is making it clear in the code that most of the tweaks don't contribute Elo when applied to non quiet moves. Special tweaks for noisy moves might gain Elo and this opens the doors to testing them with gainer bounds
=> Remove most lmr tweaks for non quiet moves

src/search.cpp, src/types.h
STC:
Elo   | 1.71 +- 1.38 (95%)
Games | N: 65442 W: 15818 L: 15495 D: 34129
Penta | [265, 7639, 16585, 7972, 260]
https://chess.swehosting.se/test/7305/
LTC:
Elo   | 3.97 +- 2.51 (95%)
Games | N: 17940 W: 4116 L: 3911 D: 9913
Penta | [20, 2006, 4714, 2209, 21]
https://chess.swehosting.se/test/7309/
Bench 5701669
=> Tweak tactical LMR with history

src/eval.h, src/movepicker.cpp, src/types.h
Original idea (and promising test results) from SF, see: https://github.com/official-stockfish/Stockfish/pull/5449
Appeared incredibly neutral st STC but the fishtest results warranted a speculative LTC, passed the speculative LTC
Elo   | 2.20 +- 1.69 (95%)
Games | N: 40008 W: 9092 L: 8839 D: 22077
Penta | [41, 4619, 10439, 4856, 49]
Bench: 5647256
=> Introduction evaluation grain of 16

src/search.cpp
passed gainer bounds stc, passed the palm reading test
Elo   | 3.12 +- 2.20 (95%)
Games | N: 25834 W: 6233 L: 6001 D: 13600
Penta | [73, 3049, 6465, 3233, 97]
Bench: 5844491
=> Simplify !inCheck condition for LMP

src/search.cpp
passed gainer bounds STC
Elo   | 4.75 +- 2.86 (95%)
Games | N: 15304 W: 3761 L: 3552 D: 7991
Penta | [64, 1710, 3888, 1933, 57]
passed simplification bounds LTC
Elo   | 1.10 +- 1.91 (95%)
LLR   | 3.3175 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 30858 W: 6999 L: 6901 D: 16958
Penta | [34, 3552, 8149, 3670, 24]
Bench: 5211058
=> Remove depth guard from LMP

src/makemove.cpp, src/movegen.cpp, src/position.cpp, src/position.h, src/search.cpp
Elo   | -0.48 +- 2.28 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=16MB
LLR   | 0.09 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 25550 W: 6385 L: 6420 D: 12745
Penta | [185, 2939, 6548, 2932, 171]
Bench: 5211058
=> Add getters for all board state variables

src/search.cpp, src/types.h
Elo   | 4.92 +- 2.91 (95%)
Games | N: 14632 W: 3558 L: 3351 D: 7723
Penta | [37, 1665, 3746, 1790, 78]
Elo   | 1.17 +- 0.92 (95%)
Games | N: 131098 W: 29414 L: 28972 D: 72712
Penta | [81, 15190, 34604, 15554, 120]
Bench: 5169868
=> Fail saved RFP

src/search.cpp
STC:
Elo   | 3.67 +- 3.25 (95%)
Games | N: 10310 W: 2481 L: 2372 D: 5457
Penta | [20, 1068, 2879, 1159, 29]
LTC:
Elo   | 0.68 +- 1.69 (95%)
Games | N: 35812 W: 7980 L: 7910 D: 19922
Penta | [20, 3820, 10158, 3886, 22]
Bench: 5389308
=> Remove nonPawns guard for forward pruning

src/search.cpp
Elo   | 2.98 +- 3.00 (95%)
LLR   | 2.90 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 12360 W: 3007 L: 2901 D: 6452
Penta | [32, 1286, 3455, 1358, 49]
Elo   | -0.11 +- 1.22 (95%)
LLR   | 1.63 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 64422 W: 14381 L: 14401 D: 35640
Penta | [37, 6500, 19156, 6482, 36]
Bench: 6083794
=> Simplify QS futility pruning conditions

src/search.cpp
failed STC:
Elo   | -2.05 +- 2.30 (95%)
LLR   | -2.30 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 23570 W: 5593 L: 5732 D: 12245
Penta | [86, 2911, 5920, 2792, 76]
passed LTC:
Elo   | 0.38 +- 1.50 (95%)
LLR   | 2.92 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 49844 W: 11468 L: 11414 D: 26962
Penta | [24, 5879, 13073, 5911, 35]
Bench: 6899697
=> Remove pv node guard from lmp

src/simd.h, src/types.h
Elo   | 0.86 +- 1.83 (95%)
Games | N: 31590 W: 7597 L: 7519 D: 16474
Penta | [64, 3309, 8971, 3387, 64]
=> Simplify avx2 sum reduction

src/nnue.cpp, src/types.h
Elo   | 3.35 +- 2.30 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=16MB
Games | N: 23658 W: 6190 L: 5962 D: 11506
Penta | [121, 2573, 6239, 2749, 147]
https://chess.swehosting.se/test/9335/
bench 8476323
=> Speed up finny table refreshes

src/history.cpp, src/history.h, src/search.cpp, src/types.h
Passed STC:
Elo   | 3.50 +- 2.35 (95%)
Games | N: 21930 W: 5408 L: 5187 D: 11335
Penta | [66, 2508, 5590, 2741, 60]
Passed LTC:
Elo   | 6.82 +- 3.44 (95%)
Games | N: 9380 W: 2261 L: 2077 D: 5042
Penta | [4, 1018, 2464, 1198, 6]
Bench: 6442362
=> Keepstealing

src/search.cpp, src/types.h
Passed STC:
Elo   | 1.99 +- 1.58 (95%)
Games | N: 49622 W: 12120 L: 11836 D: 25666
Penta | [139, 5862, 12570, 6056, 184]
likely at least neutral at LTC:
Elo: 0.98 (-2.39 / +2.39) [-1.41 to 3.36]
nElo: 2.03 (-4.96 / +4.96) [-2.93 to 6.98]
Gamepairs Elo: 1.47 (-4.75 / +4.75) [-3.27 to 6.22]
Normalized Pair Elo: 1.06
LLR: 3.5367
=> Guard less moves from lmr

src/search.cpp, src/search.h
Elo   | 3.32 +- 2.45 (95%)
SPRT  | 60.0+0.60s Threads=1 Hash=64MB
LLR   | 2.90 (-2.25, 2.89) [0.00, 4.00]
Games | N: 17980 W: 4224 L: 4052 D: 9704
Penta | [5, 1994, 4821, 2164, 6]
https://chess.swehosting.se/test/9507/
Bench 8669143
=> Tweak SE parameters

src/search.cpp, src/tune.h
=> Divide rfp formula into subcomponents

src/history.cpp, src/history.h, src/move.h, src/search.cpp, src/types.h
Fixes a rare chkstk crash on windows.
Passed STC non regr:
Elo   | 1.42 +- 1.66 (95%)
LLR   | 5.20 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 40020 W: 9805 L: 9641 D: 20574
Penta | [111, 4218, 11200, 4358, 123]
=> Reduce stack usage

src/eval.h, src/types.h
Elo   | 2.55 +- 1.91 (95%)
Games | N: 33716 W: 8303 L: 8056 D: 17357
Penta | [97, 3934, 8559, 4161, 107]
Elo   | 1.74 +- 1.40 (95%)
Games | N: 55766 W: 12865 L: 12585 D: 30316
Penta | [30, 6330, 14886, 6604, 33]
Bench: 9973272
=> Use material value based scaling over phase based scaling

src/time_manager.cpp, src/tune.h, src/types.h
Passed non regression STC:
Elo   | 10.67 +- 5.38 (95%)
LLR   | 2.92 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 3942 W: 1021 L: 900 D: 2021
Penta | [15, 374, 1065, 509, 8]
Passed non regression LTC:
Elo   | 5.66 +- 3.90 (95%)
Games | N: 6748 W: 1609 L: 1499 D: 3640
Penta | [2, 683, 1896, 789, 4]
Passed gainer bounds STC:
Elo   | 4.26 +- 2.62 (95%)
Games | N: 16564 W: 4126 L: 3923 D: 8515
Penta | [41, 1746, 4519, 1921, 55]
Passed gainer bounds LTC:
Elo   | 5.84 +- 3.06 (95%)
Games | N: 10292 W: 2418 L: 2245 D: 5629
Penta | …
=> Simplify tm, use maxtime bound as the hardtime bound

src/threads.h, src/time_manager.cpp
Adds a return to avoid one level of indentation later on, makes the meaning of checking for movesToGo more explicit and removes a non functional std::max call.
=> Make tm code easier to read

src/bench.cpp, src/search.cpp, src/types.h
failed STC gainer bounds:
Elo   | -1.11 +- 2.17 (95%)
LLR   | -2.28 (-2.25, 2.89) [0.00, 3.00]
Games | N: 24646 W: 5838 L: 5917 D: 12891
Penta | [62, 2861, 6566, 2762, 72]
passed LTC gainer bounds:
Elo   | 2.05 +- 1.59 (95%)
Games | N: 41666 W: 9558 L: 9312 D: 22796
Penta | [26, 4522, 11481, 4788, 16]
=> Reintroduce draw score randomization

src/search.cpp, src/types.h
I'm sure this scales at some point
Passed STC gainer bounds:
Elo   | 3.39 +- 2.28 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 3.00]
Games | N: 22856 W: 5395 L: 5172 D: 12289
Penta | [49, 2618, 5871, 2841, 49]
Dead neutral at LTC:
Elo   | 0.03 +- 2.21 (95%)
LLR   | -0.78 (-2.25, 2.89) [0.00, 3.00]
Games | N: 21922 W: 4824 L: 4822 D: 12276
Penta | [7, 2506, 5930, 2514, 4]
Bench: 6623357
=> Qs stand pat failfirm

src/search.cpp
Elo   | 0.96 +- 1.92 (95%)
LLR   | 3.0668 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 31896 W: 7352 L: 7264 D: 17280
Penta | [73, 3717, 8277, 3811, 70]
Elo   | 1.41 +- 2.07 (95%)
LLR   | 3.2660 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 25118 W: 5715 L: 5613 D: 13790
Penta | [10, 2833, 6769, 2939, 8]
Bench: 6417573
=> Remove depth guard from nmp

src/tune.h
Elo   | 2.71 +- 2.96 (95%)
LLR   | 2.89 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 13850 W: 3299 L: 3191 D: 7360
Penta | [36, 1596, 3569, 1672, 52]
Bench: 6809244
=> Adjust out of scale Capthist malus multiplier

src/history.cpp, src/io.cpp, src/makemove.cpp, src/nnue.cpp, src/position.cpp, src/position.h, src/search.cpp
Cleaner code, strictly faster computation wise.
Elo   | 1.09 +- 1.18 (95%)
LLR   | 1.48 (-2.25, 2.89) [0.00, 3.00]
Games | N: 76708 W: 17809 L: 17568 D: 41331
Penta | [151, 8093, 21630, 8324, 156]
Bench: 6809244
=> Avoid copying back the position during UnmakeMove in favour of popping the stack

src/search.cpp
Very bad at STC:
Elo   | -4.15 +- 3.40 (95%)
LLR   | -2.28 (-2.25, 2.89) [0.00, 3.00]
Games | N: 8876 W: 1951 L: 2057 D: 4868
Penta | [13, 986, 2544, 884, 11]
Neutral at LTC:
Elo   | -0.10 +- 1.36 (95%)
LLR   | -2.03 (-2.25, 2.89) [0.00, 3.00]
Games | N: 46912 W: 10253 L: 10267 D: 26392
Penta | [15, 4343, 14748, 4341, 9]
Neutral enough at 60s:
Elo   | -0.81 +- 1.97 (95%)
SPRT  | 60.0+0.60s Threads=1 Hash=64MB
LLR   | -1.82 (-2.25, 2.89) [0.00, 3.00]
Games | N: 21426 W: 4662 L: 4712 D: 12052
Penta | [6, 1926, 6896, 1882, 3]
=> Partially prevent graph history interaction

src/makemove.cpp, src/position.cpp, src/search.cpp
Elo   | 0.39 +- 1.94 (95%)
LLR   | 1.63 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 27026 W: 6271 L: 6241 D: 14514
Penta | [48, 2770, 7842, 2810, 43]
Cosmo said it was good enough
Bench: 6738798
=> Use keyAfter for nmp

src/misc.h, src/position.cpp, src/uci.cpp
fixes an issue where fens without the 50mr and fullmove counter (but a "moves" token) would lead to a stoi exception.
Example fen: `position fen 5rk1/2p4p/2p4r/3P4/4p1b1/1Q2NqPp/PP3P1K/R4R2 b - - moves`.
closes #566. 
Bench: 9118561
=> Fix partial fen handling

src/search.cpp
Elo   | 0.55 +- 1.68 (95%)
LLR   | 2.92 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 42436 W: 10227 L: 10160 D: 22049
Penta | [113, 5032, 10850, 5121, 102]
Bench: 8600154
=> Enforce Qsearch fail mid consistency

src/search.cpp
Possibly quite bad at STC:
Elo   | -3.42 +- 3.83 (95%)
LLR   | -1.55 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 8232 W: 1934 L: 2015 D: 4283
Penta | [21, 1032, 2088, 957, 18]
Neutral (at least) at LTC:
Elo   | 1.63 +- 2.32 (95%)
Games | N: 20244 W: 4735 L: 4640 D: 10869
Penta | [11, 2281, 5441, 2380, 9]
Bench: 8823740
=> Allow triple extension of tactical moves

src/movepicker.cpp, src/movepicker.h, src/types.h
Elo   | 2.04 +- 2.41 (95%)
LLR   | 2.94 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 16024 W: 3835 L: 3741 D: 8448
Penta | [22, 1472, 4935, 1556, 27]
Bench: 8823740
=> Remove bad capture movelist from movepicker
