PGG106/Alexandria

Dockerfile
This allows for easy deployment of Alexandria to servers.
=> Adds Docker Support to Alexandria.

src/search.cpp
the change is too small to be tested accurately, with some bias expecting the change to be good it gets into acceptable range, might return to this in the future if i ever get enough testing power 
ELO   | 2.04 +- 3.48 (95%)
LLR   | 0.07 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 20760 W: 5717 L: 5595 D: 9448
=> tweak history heuristic and move scoring

src/Board.h, src/move.h, src/search.cpp
ELO   | 16.45 +- 13.35 (95%)
LLR   | 3.02 (-2.94, 2.94) [-10.00, 0.00]
GAMES | N: 1184 W: 297 L: 241 D: 646
=> Improve history heuristic and add movecount pruning

src/move.h, src/search.cpp
ELO   | 33.51 +- 12.11 (95%)
GAMES | N: 1456 W: 404 L: 264 D: 788
=> Use a conditional jump when the position is in check

src/search.cpp, src/ttable.cpp
ELO   | 10.62 +- 6.39 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 5304 W: 1322 L: 1160 D: 2822
=> avoid unnecessary legality check when probing a TT move

src/search.cpp, src/ttable.cpp
ELO   | 13.39 +- 7.19 (95%)
GAMES | N: 3920 W: 934 L: 783 D: 2203
=> Master return change

src/search.cpp
ELO   | 69.60 +- 17.74 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 688 W: 227 L: 91 D: 370
=> scale nmp reduction factor with depth

src/search.cpp, src/ttable.cpp
ELO   | 19.20 +- 8.60 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 2608 W: 615 L: 471 D: 1522
=> Probe cleanup2

src/search.cpp
ELO   | 12.43 +- 6.71 (95%)
GAMES | N: 4112 W: 895 L: 748 D: 2469
=> Reduce lmr when improving

src/makefile, src/search.cpp, src/uci.cpp
this nets a speed up of around 5-10% with no functional search change
=> use a separate thread to handle uci commands

src/search.cpp, src/uci.cpp
ELO   | 4.44 +- 3.51 (95%)
GAMES | N: 17752 W: 4314 L: 4087 D: 9351
=> Remove evaluation pruning

src/search.cpp, src/uci.cpp
* remove evaluation pruning
* clean ep code remnants
=> Remove evaluation pruning (#37)

src/search.cpp
ELO   | 4.87 +- 3.79 (95%)
GAMES | N: 15208 W: 3695 L: 3482 D: 8031
=> History pruning

src/Board.cpp, src/makemove.cpp, src/nnue.cpp, src/nnue.h
ELO   | 5.62 +- 4.21 (95%)
GAMES | N: 12112 W: 2912 L: 2716 D: 6484
=> Batch update Nnue in case of moved pieces

src/search.cpp
=> remove countermove heuristic

src/search.cpp, src/uci.cpp
ELO   | 9.16 +- 5.97 (95%)
GAMES | N: 6600 W: 1765 L: 1591 D: 3244
=> Simplify razoring condition 

src/search.cpp
ELO   | 3.79 +- 3.05 (95%)
GAMES | N: 24496 W: 6163 L: 5896 D: 12437
=> Add additional conditions to shallow pruning

src/Board.h, src/History.cpp, src/History.h, src/bench.cpp, src/main.cpp, src/movegen.h, src/search.cpp, src/search.h, src/ttable.cpp, src/ttable.h, src/uci.cpp, src/uci.h
=> separate some of the search info from the board structure

src/Board.cpp, src/Board.h, src/search.cpp, src/time_manager.cpp, src/time_manager.h, src/uci.cpp
ELO   | 25.42 +- 10.75 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 2040 W: 592 L: 443 D: 1005
ELO   | 15.23 +- 7.87 (95%)
GAMES | N: 3448 W: 871 L: 720 D: 1857
Bench: 6716375
=> Use a different TM strategy

src/search.cpp
ELO   | 6.84 +- 4.97 (95%)
GAMES | N: 9952 W: 2739 L: 2543 D: 4670
=> increase LMR reduction on non Pv nodes

src/search.cpp
* reduce more on non pv nodes
* refactor lmr code
Bench: 5442020
=> increase LMR reduction on non Pv nodes (#55)

src/search.cpp
=> use static eval instead of tt score for some heuristics

src/search.cpp
=> Stop checking if move exists before returning TT score

src/search.cpp
=> don't nmp if there's only pawns on the board

src/History.cpp
=> Cap history score to +-32768

src/Board.cpp, src/Board.h, src/search.cpp, src/time_manager.cpp, src/time_manager.h, src/uci.cpp
ELO   | 37.00 +- 13.36 (95%)
GAMES | N: 1376 W: 435 L: 289 D: 652
=> Introduce a more complex TM

src/search.cpp
=> fix standing pat

src/search.cpp
=> fix see for quiet moves

src/search.cpp
ELO   | 20.77 +- 9.58 (95%)
GAMES | N: 2496 W: 690 L: 541 D: 1265
=> Bench: 7450731

src/search.cpp
ELO   | 18.88 +- 9.02 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
GAMES | N: 2800 W: 764 L: 612 D: 1424
Bench: 5806085
=> add See pruning to qsearch

src/time_manager.cpp
=> Reduce checks for time running out to once every 1024 nodes

src/History.cpp, src/search.cpp
Big thanks to Disservin for helping me spotting the issue and cosmo for suggesting the use of a quadratic term
=> Rework history heuristic

src/search.cpp
=> change nmp to fail soft

src/perft.cpp, src/uci.cpp
=> avoid perft crashing when called with a depth of 1

src/uci.cpp
```
setoption name multipv value 2
Unknown command: setoption name multipv value 2
```
=> Add OPTION UCI "Unknown command"

src/search.cpp
=> Rewrite LMR with a more conventional approach

src/History.cpp, src/History.h, src/init.cpp, src/search.cpp, src/search.h, src/uci.cpp
```
ELO   | 17.79 +- 8.71 (95%)
GAMES | N: 2952 W: 788 L: 637 D: 1527
```
=> Introduce continuation history

src/datagen.cpp, src/uci.cpp
=> Set a default limit for datagen

src/movepicker.cpp, src/search.h
ELO   | 25.48 +- 10.69 (95%)
GAMES | N: 2008 W: 569 L: 422 D: 1017
Bench: 5206870
=> fix movepicker

src/datagen.cpp, src/datagen.h, src/io.cpp, src/threads.h, src/uci.cpp
=> Make the datagen process stoppable by the end user

src/movepicker.cpp, src/search.cpp
ELO   | 5.06 +- 3.86 (95%)
GAMES | N: 13792 W: 3165 L: 2964 D: 7663
=> Make lmr more aggressive on non pv nodes

src/search.cpp
Use cached eval from TT when possible, Prefetch moves
=> Refactor Qsearch

src/init.cpp, src/makemove.cpp, src/nnue.cpp, src/perft.cpp, src/time_manager.cpp
ELO   | 4.64 +- 3.17 (95%)
GAMES | N: 21856 W: 5320 L: 5028 D: 11508
ELO   | 8.29 +- 5.62 (95%)
LLR   | 1.83 (-2.94, 2.94) [0.00, 3.00]
GAMES | N: 6536 W: 1535 L: 1379 D: 3622
Bench: 2924659
=> Make lmp more aggressive

src/search.cpp, src/search.h
ELO   | 13.72 +- 6.14 (95%)
GAMES | N: 6408 W: 1800 L: 1547 D: 3061
=> Allow limited double extensions

src/search.cpp
=> Make double extensions limit have more sense

src/search.cpp
=> Guard pv nodes from captures lmr

src/board.cpp, src/board.h, src/datagen.cpp, src/history.cpp, src/history.h, src/init.cpp, src/makemove.cpp, src/nnue.cpp, src/search.cpp, src/search.h, src/ttable.cpp, src/ttable.h
saves a few lines of code and should technically be slightly faster
=> Move ply counter into the search stack

src/search.cpp
ELO   | 1.84 +- 1.44 (95%)
GAMES | N: 109944 W: 27567 L: 26984 D: 55393
Bench: 3229242
=> Clean killers for the next ply 

src/init.cpp
ELO   | 5.16 +- 3.43 (95%)
GAMES | N: 19520 W: 4981 L: 4691 D: 9848
=> Make lmr formula less aggressive 

src/makemove.cpp
=> Remove some branching in makemove

src/search.cpp
ELO   | 7.49 +- 4.28 (95%)
GAMES | N: 12432 W: 3196 L: 2928 D: 6308
ELO   | 7.48 +- 4.24 (95%)
GAMES | N: 12132 W: 2994 L: 2733 D: 6405
Bench: 11200449
=> Extend movecount pruning to tactical moves 

src/search.cpp
ELO   | 9.67 +- 6.31 (95%)
LLR   | 2.96 (-2.94, 2.94) [-3.00, 1.00]
GAMES | N: 5680 W: 1465 L: 1307 D: 2908
Bench: 11164456
=> Check for bounds before adjusting eval

src/search.cpp
=> Simplify lmr

src/search.cpp
ELO   | 2.80 +- 2.20 (95%)
GAMES | N: 46208 W: 11364 L: 10991 D: 23853
Bench: 10550768
=> Improve improving

src/move.cpp, src/search.cpp, src/ttable.cpp, src/ttable.h
ELO   | 1.66 +- 1.26 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 3.00]
GAMES | N: 143328 W: 35346 L: 34661 D: 73321
=> Pack move into 16bits before saving to the TT

Contributors, src/search.cpp, src/types.h
=> Fix formatting

src/search.cpp, src/types.h
=> Fix potential TT race issues

src/eval.cpp, src/search.cpp, src/types.h
FEN: 8/8/3B4/5k2/8/5r1b/7K/8 w - - 8 70
Before:
```
21/30    122ms  395.15Kn       -1.40   3238kn/s d6g3 h3f1 g3d6 f5e4 d6g3 e4d3 g3c7 f1h3 c7b6 d3c4 b6c7 h3d7 h2g2 d7c6 g2g1 c4c3 c7e5 c3d3 e5c7 d3c4 c7b6 f3f7 b6f2 f7g7
22/34    369ms    1.26Mn       -M19   3420kn/s d6g3 f5g4 g3c7 f3f7 c7b8 g4f3 h2g1 f7g7 g1h2 g7h7 h2g1 h3g2 b8h2 h7h3 h2g3 h3g3 g1h2 g3g8 h2g1 g2h3 g1h1 f3e4 h1h2 h3f1
23/36    502ms    1.77Mn       -4.33   3526kn/s h2g1 f5e4 g1h2 f3f6 d6c5 f6f5 c5a7 f5f7 h2h3 f7a7 h3g4 a7g7 g4h5 g7g8 h5h6 g8g1 h6h7 e4e3 h7h6 e3d4 h6h5 g1g8 h5h6 g8g4
24/36    578ms    2.05Mn       -M30   3550kn/s h2g1 f5e4 g1h2 f3f6 d6c5 f6f5 c5a7 f5f7 h2h3 f7a7 h3g2 e4e3 g2g3 a7g7 g3h4 g7g8 h4h5 e3e4 h5h6 g8g1 h6h5 e4d4 h5h6 g1g4 h6h5 g4g7 h5h6 g7g1 h6h5 g1g8
25/36    579ms    2.06Mn       -M31   3551kn/s …
```
=> Remove razoring, clamp evaluation, fix Qsearch SEE pruning

src/search.cpp
No functional change. 
Bench 11074335
=> Remove unneeded eval variable in qsearch

src/io.cpp, src/search.cpp, src/search.h, src/ttable.h, src/types.h
=> Prevent wrong TT flags when not TT hit (#237)

src/search.cpp
ELO   | 1.71 +- 1.32 (95%)
SPRT  | 5.0+0.05s Threads=1 Hash=16MB
GAMES | N: 131648 W: 32992 L: 32343 D: 66313
Bench: 9202804
=> Use a weighted average of the previous eval for the aspiration windows

src/init.cpp, src/search.cpp, src/types.h
```
ELO   | 5.11 +- 4.76 (95%)
GAMES | N: 9936 W: 2490 L: 2344 D: 5102
https://chess.swehosting.se/test/3907/
```
Bench 9589773
=> Simplify and clean up LMR

src/history.cpp, src/types.h
ELO | 2.81 +- 2.23 (95%)
SPRT | 8.0+0.08s Threads=1 Hash=16MB
LLR | 2.89 (-2.25, 2.89) [0.00, 3.00]
Bench: 9119715
=> Extend continuation history to 4 plies (#245)

src/search.cpp
1. Replace all tabs with spaces in search
2. Change some cases
3. Fix some incorrect variable namings
Bench: 8913775
=> Small cleanups

src/init.cpp, src/io.cpp, src/search.cpp, src/search.h, src/time_manager.cpp
=> Further improvements to formatting and comments

src/search.cpp, src/types.h
Elo   | 5.37 +- 4.10 (95%)
Games | N: 13576 W: 3446 L: 3236 D: 6894
Penta | [69, 1514, 3433, 1682, 90]
Bench: 8440042
=> Stop penalizing moves that weren't actually played 

src/board.h
=> Fix indentation

src/init.cpp
No functional change
Bench 8440042
=> Tweak LMP init

src/search.cpp, src/types.h
Elo   | 2.68 +- 3.88 (95%)
LLR   | 3.03 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 14918 W: 3686 L: 3571 D: 7661
Penta | [75, 1677, 3840, 1792, 75]
=> Simplify lmp

makefile
Makes machines on swehosting unable to compile
Bench: 9021430
=> Revert recent makefile changes

makefile
=> Revert recent makefile changes (#285)

src/search.cpp, src/types.h
Elo   | 4.03 +- 4.60 (95%)
LLR   | 3.00 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 10596 W: 2631 L: 2508 D: 5457
Penta | [51, 1203, 2712, 1236, 96]
LTC pending, will maybe be added at one point idk.
Bench: 6796017
=> Yeet check extension

src/board.cpp, src/board.h, src/init.cpp, src/makemove.cpp, src/movegen.cpp, src/types.h
makes check mask handling less error prone
Bench: 6645600
=> Simplify Check mask handling

src/board.cpp, src/board.h, src/makemove.cpp, src/makemove.h, src/types.h
temporary questionable fix for the issue, a makemove template is a better idea and should be implemented in the near future
=> Fix Stack overflow in games with more than 256 moves

src/search.cpp, src/types.h
Elo   | 8.68 +- 5.41 (95%)
Games | N: 7204 W: 1732 L: 1552 D: 3920
Penta | [9, 730, 1944, 910, 9]
Bench: 7202844
=> SF do deeper

src/board.cpp, src/makemove.cpp, src/movegen.cpp, src/movegen.h, src/movepicker.cpp, src/movepicker.h, src/search.cpp, src/types.h
ELO   | 2.53 +- 2.04 (95%)
GAMES | N: 53344 W: 13034 L: 12645 D: 27665
https://chess.swehosting.se/test/5274/
Bench 7592451
=> Add staged movegen for the TT move

src/nnue.cpp, src/search.cpp
Also makes certain behaviours explicit
Bench: 7592451
=> Small simplifications

src/movegen.cpp
=> Fix legal detection on double check

src/movegen.cpp
If we are not in check then of course our king cannot be attacked
Bench 7592451
=> Simplify castling movegen

src/makemove.cpp, src/nnue.cpp, src/search.cpp, src/search.h, src/types.h
Avoid updating the acc if we leave a node early, possible reasons may include a TT cutoff, i didn't write a single line of this, i'm just stealing credit
=> Delay NNUE update until we actually need to get an eval

src/makemove.cpp, src/nnue.cpp, src/search.cpp, src/types.h
ELO   | 8.90 +- 4.72 (95%)
GAMES | N: 9760 W: 2415 L: 2165 D: 5180
Bench: 7592451
---------
=> Delay NNUE update until we actually need to get an eval (#305)

src/eval.cpp, src/eval.h, src/search.cpp
Simplify commit https://github.com/PGG106/Alexandria/commit/55b8575e1081622d90cbcece7c63b3427d9c2683
Bench 7513941
=> Tidy up accumulator updates

src/board.cpp, src/board.h, src/makemove.cpp, src/search.cpp, src/types.h
Elo   | 11.53 +- 6.50 (95%)
Games | N: 5424 W: 1434 L: 1254 D: 2736
Penta | [19, 500, 1498, 672, 23]
=> Prefetch before makemove

src/io.cpp, src/search.cpp, src/ttable.cpp, src/ttable.h
Secure a spot for the shredder barbecue
=> Add Hashfull to the uci output

makefile, src/types.h
=> Simplify makefile

makefile, src/nnue.cpp
Clang compile technically works but will not embed the net
=> Further simplify the makefile, add partial clang compilation support

src/search.cpp, src/types.h
Elo   | 3.02 +- 2.86 (95%)
Games | N: 26142 W: 6172 L: 5945 D: 14025
Penta | [66, 2930, 6879, 3103, 93]
=> Guard less moves from lmr

src/board.cpp, src/movegen.cpp
functionally identic but less terrible to look at
=> Ditch the inherited SF defines for popcount and lsb in favour of C++20 stdlib functions

src/search.cpp
=> Improve formatting slightly

src/movepicker.cpp, src/search.cpp
Easier to do pre moves-loop searches
Bench 6213685
=> Move NNUE updates

src/board.cpp
Use the given side instead of pos->side
Bench 6445111
=> Fix getThreats function

src/tune.cpp, src/uci.cpp
=> Fix and improve tuning setup

Contributors
=> Update contributors file and fix ordering

makefile
=> Cleanup and re-align makefile

src/board.cpp, src/board.h, src/search.cpp, src/types.h
=> Fix oppCanWinMaterial function

src/bench.cpp, src/bench.h, src/main.cpp, src/uci.cpp, src/uci.h
=> Add support for custom depth bench

src/search.cpp
Use totalMoves instead, and account for the offset by one
Elo   | 0.36 +- 2.74 (95%)
LLR   | 1.64 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 29308 W: 7012 L: 6982 D: 15314
Penta | [146, 3350, 7618, 3408, 132]
https://chess.swehosting.se/test/5558/
However, it passes [-5, 0]
```
$ python3 sprt.py --wins 7012 --losses 6982 --draws 15314 --elo0 -5 --elo1 0
ELO: 0.356 +- 2.74 [-2.39, 3.1]
LLR: 4.02 [-5.0, 0.0] (-2.94, 2.94)
H1 Accepted
```
Bench: 6133386
=> Remove movesSearched variable

src/nnue.cpp, src/nnue.h, src/types.h
No functional change
Bench 5740933
=> Simplify SIMD code slightly

makefile
=> Fix makefile for macOS which has a different native flag

src/eval.cpp, src/io.cpp, src/movepicker.cpp, src/movepicker.h, src/search.cpp, src/ttable.cpp, src/ttable.h, src/types.h
No functional change
Bench 6110305
=> Cleanup TT and constant namings

src/board.cpp, src/board.h, src/makemove.cpp, src/movegen.cpp, src/movegen.h, src/movepicker.cpp, src/perft.cpp, src/search.cpp, src/types.h
Also a huge cleanup to quite a bit of movegen code
Elo   | 6.82 +- 4.67 (95%)
Games | N: 10290 W: 2593 L: 2391 D: 5306
Penta | [40, 1110, 2670, 1258, 67]
https://chess.swehosting.se/test/5674/
Bench 6080200
=> Switch to pseudo-legal movegen

src/board.h, src/history.cpp, src/init.cpp, src/movepicker.cpp, src/nnue.cpp, src/nnue.h, src/search.cpp, src/search.h, src/types.h
=> Cleanup variable naming + NNUE updates

src/ttable.cpp, src/ttable.h, src/types.h
Passed STC:
Elo   | 2.47 +- 2.45 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 3.00]
Games | N: 36890 W: 8957 L: 8695 D: 19238
Penta | [152, 4190, 9501, 4448, 154]
https://chess.swehosting.se/test/5789/
Passed LTC:
Elo   | 10.52 +- 6.02 (95%)
Games | N: 5816 W: 1411 L: 1235 D: 3170
Penta | [5, 553, 1621, 719, 10]
https://chess.swehosting.se/test/5792/
Bench 6550747
=> Implement buckets in TT

src/search.cpp
=> Fix mate detection at 50 move rule

src/ttable.cpp
Hopefully fixes compilation for @raklaptudirm
Bench 6550747
=> Remove unneeded include

src/nnue.cpp, src/nnue.h
=> Guard immintrin.h include

src/board.cpp, src/board.h, src/makemove.cpp
=> Rework history stack indexing

src/bench.cpp, src/init.cpp, src/movegen.cpp, src/movepicker.cpp, src/movepicker.h, src/perft.cpp, src/search.cpp, src/ttable.cpp, src/ttable.h, src/uci.cpp
=> Cleanup initialisations

src/search.cpp, src/types.h
Elo   | 3.23 +- 2.95 (95%)
Games | N: 24612 W: 5811 L: 5582 D: 13219
Penta | [85, 2721, 6497, 2886, 117]
https://chess.swehosting.se/test/5856/
Bench 6562652
=> Tweak repetition detection

src/move.cpp, src/move.h, src/movegen.cpp, src/movegen.h, src/movepicker.cpp, src/movepicker.h, src/perft.cpp, src/search.cpp, src/types.h, src/uci.cpp
Elo   | 7.69 +- 4.90 (95%)
Games | N: 9132 W: 2262 L: 2060 D: 4810
Penta | [31, 1028, 2265, 1192, 50]
https://chess.swehosting.se/test/5968/
Bench 6587803
=> Fully staged movepicker

src/position.cpp, src/position.h, src/search.cpp, src/types.h
=> update branch (#387)

src/movepicker.cpp, src/types.h
Elo   | 1.71 +- 1.82 (95%)
Games | N: 66788 W: 16175 L: 15846 D: 34767
Penta | [227, 8016, 16615, 8273, 263]
https://chess.swehosting.se/test/6155/
Bench 6159523
=> Remove duplicate refutations being searched

src/movepicker.cpp, src/movepicker.h, src/search.cpp
We only have one killer anyways so we don't really need a 0 at the end
Bench 6735520
=> Rename killer0 to killer

src/search.cpp
=> Don't check for search being stopped after a null move 

src/random.h
=> Small fix on RNG

src/attack.cpp, src/attack.h, src/cuckoo.cpp, src/cuckoo.h, src/init.cpp, src/position.cpp, src/position.h, src/search.cpp, src/types.h
Elo   | 2.76 +- 2.61 (95%)
Games | N: 30738 W: 7093 L: 6849 D: 16796
Penta | [73, 3598, 7807, 3794, 97]
=> Add upcoming repetition detection via cuckoo tables

src/eval.cpp, src/makemove.cpp, src/movepicker.cpp, src/nnue.cpp, src/nnue.h, src/position.h, src/types.h
Elo   | 10.98 +- 4.42 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 3.00]
Games | N: 5920 W: 1502 L: 1315 D: 3103
Penta | [20, 568, 1597, 755, 20]
https://chess.swehosting.se/test/6732/
Bench 5966004
=> Do not needlessly copy the accumulator when doing incremental updates

src/ttable.cpp
Title, closes #406 
Bench: 7027744
=> Fix compilation on non x86 target machines

src/eval.cpp, src/makemove.cpp, src/movepicker.cpp, src/nnue.cpp, src/nnue.h, src/position.cpp, src/position.h, src/types.h, src/uci.cpp
Elo   | 4.04 +- 2.55 (95%)
Games | N: 18568 W: 4417 L: 4201 D: 9950
Penta | [69, 2024, 4896, 2212, 83]
https://chess.swehosting.se/test/6863/
Bench 6519222
=> Delay incremental updates by multiple plies if we do not need an eval

src/movegen.cpp
Elo   | 1.19 +- 2.39 (95%)
LLR   | 2.26 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 20130 W: 4679 L: 4610 D: 10841
Penta | [55, 2242, 5410, 2295, 63]
=> Improve const correctness 

src/makemove.cpp, src/makemove.h, src/perft.cpp, src/position.cpp, src/search.cpp
Elo   | 0.43 +- 1.72 (95%)
LLR   | 2.43 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 39162 W: 9042 L: 8993 D: 21127
Penta | [117, 4375, 10554, 4412, 123]
https://chess.swehosting.se/test/6943/
=> Obsolete MakeUCIMove function

src/move.cpp, src/move.h, src/movegen.cpp, src/movepicker.cpp, src/movepicker.h, src/search.cpp, src/ttable.cpp, src/ttable.h, src/types.h
=> Make "Move" type unsigned and introduce "PackedMove" type

src/history.cpp, src/position.h, src/search.h, src/uci.h
=> Move PvTable into search.h and use "Move" to store moves instead of "int"

makefile
=> Re-align makefile

src/search.cpp
=> Fix static eval being reset during singular search

src/search.cpp
=> Remove goto usage

Contributors, src/init.cpp, src/io.cpp, src/search.cpp, src/types.h, src/uci.cpp
please test, my elo estimate 0.5-1.0
Bench: 6118297
=> use line buffering

src/nnue.cpp, src/nnue.h
Elo   | 3.28 +- 3.21 (95%)
Games | N: 12070 W: 2950 L: 2836 D: 6284
Penta | [51, 1359, 3100, 1475, 50]
Bench: 5778419
=> Remove unneeded function

src/init.cpp, src/nnue.cpp, src/nnue.h, src/search.cpp
passed non regression STC
Elo   | 1.30 +- 2.21 (95%)
LLR   | 2.89 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 24600 W: 5893 L: 5801 D: 12906
Penta | [91, 2782, 6460, 2878, 89]
Bench: 5211058
=> Remove output buffering

src/makemove.cpp, src/nnue.cpp, src/position.cpp, src/position.h, src/search.cpp
=> Group position board state variables into a struct

src/position.cpp
=> Simplify the copy/make section of makemove

makefile
=> Support VNNI in the makefile

src/search.cpp
Elo   | 0.86 +- 1.16 (95%)
LLR   | 8.2162 (-2.25, 2.89) [0.00, 3.00]
Games | N: 93732 W: 22973 L: 22742 D: 48017
Penta | [330, 11244, 23494, 11461, 337]
Bench: 5205270
=> Decouple IIR position from its interaction with RFP and NMP 

src/io.cpp, src/search.cpp
=> Print a final info string before reporting best move

src/attack.cpp, src/attack.h, src/movegen.cpp
Group the shared logic of all the slider pieces into a single function
Bench: 5006928
=> Simplify movegen code

src/history.cpp, src/history.h, src/movepicker.cpp, src/movepicker.h, src/search.cpp, src/search.h
Fresh Viz idea
Passed STC:
Elo   | 6.72 +- 3.46 (95%)
Games | N: 9818 W: 2408 L: 2218 D: 5192
Penta | [18, 1069, 2554, 1241, 27]
https://chess.swehosting.se/test/8480/
Passed LTC:
Elo   | 1.30 +- 1.05 (95%)
Games | N: 99660 W: 22136 L: 21764 D: 55760
Penta | [47, 11307, 26769, 11641, 66]
https://chess.swehosting.se/test/8481/
=> Introduce Root History

src/search.cpp
=> Speed up draw detection

src/history.cpp, src/makemove.cpp, src/position.cpp, src/position.h, src/search.h, src/types.h
STC [passed](https://chess.swehosting.se/test/8779/), LTC [running](https://chess.swehosting.se/test/8780/)
=> non-pawn corrhist

src/history.cpp, src/history.h, src/move.h, src/search.cpp, src/search.h, src/types.h
same again, speculatively opening with [ltc](https://chess.swehosting.se/test/8864/) running while I sleep
[stc passed](https://chess.swehosting.se/test/8862/)
=> continuation corrhist

src/ttable.cpp
=> Merge (potential) fix for apple

src/search.cpp, src/types.h
=> Make NMP more aggressive

src/movepicker.cpp
Credits to @aronpetko
bench 7071570
=> Remove useless sort

src/position.cpp
=> Fix repetition handling in ParseFen

src/makemove.cpp, src/movegen.cpp, src/position.cpp, src/position.h, src/types.h
=> Simplify movegen

src/makemove.cpp, src/nnue.cpp, src/nnue.h, src/position.h, src/search.h, src/types.h
passed STC:
Elo   | 25.87 +- 6.93 (95%)
Games | N: 2368 W: 660 L: 484 D: 1224
Penta | [3, 192, 625, 354, 10]
Bench: 6429947
=> Add Finny tables 

src/init.cpp, src/types.h
=> Remove useless see_margin table

.gitignore, src/eval.h, src/init.cpp, src/makemove.cpp, src/makemove.h, src/movegen.cpp, src/nnue.cpp, src/nnue.h, src/position.cpp, src/position.h, src/simd.h, src/uci.cpp
Test if CI errors is indeed due to this
=> Revert #514

src/position.cpp
=> Set historyStack head to 0 when resetting the board

src/position.cpp
=> Limit upcoming cycle detection to non capturing moves

src/makemove.cpp, src/movegen.cpp, src/position.cpp, src/position.h, src/search.cpp, src/types.h
Elo   | 3.92 +- 2.52 (95%)
Games | N: 18546 W: 4372 L: 4163 D: 10011
Penta | [33, 2097, 4821, 2272, 50]
Bench: 6875825
=> Exclude pinned pieces from SEE

.gitignore, src/nnue.cpp
Saves recomputation
Bench 6809244
=> Bake the L1_SIZE multiplication into index calculation

src/eval.h, src/init.cpp, src/position.h
Elo   | 2.16 +- 2.62 (95%)
SPRT  | 6.0+0.06s Threads=1 Hash=16MB
Games | N: 16264 W: 3843 L: 3742 D: 8679
Penta | [42, 1743, 4457, 1852, 38]
Bench: 6809244
=> Remove useless instance of NNUE class object

src/search.cpp
=> Remove redundant condition in quiet evasions generation

src/makemove.cpp
No functional change
Bench: 6738798
=> Don't update pin and check masks after a null move

src/types.h
gains
Elo   | 4.09 +- 2.56 (95%)
Games | N: 17064 W: 4153 L: 3952 D: 8959
Penta | [15, 1892, 4516, 2095, 14]
on top of 
Elo   | 3.27 +- 2.22 (95%)
Games | N: 22834 W: 5417 L: 5202 D: 12215
Penta | [18, 2592, 5982, 2807, 18]
Bench: 9100977
=> New net (step 2 training with LR and WDL tweaks)

src/search.cpp
=> Fully unpack the TT data into local variables
